// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/core/memory/memory.go

// Package memory is a generated GoMock package.
package memory

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	llms "github.com/oopslink/agent-go/pkg/support/llms"
)

// MockMemoryItemCodec is a mock of MemoryItemCodec interface.
type MockMemoryItemCodec struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryItemCodecMockRecorder
}

// MockMemoryItemCodecMockRecorder is the mock recorder for MockMemoryItemCodec.
type MockMemoryItemCodecMockRecorder struct {
	mock *MockMemoryItemCodec
}

// NewMockMemoryItemCodec creates a new mock instance.
func NewMockMemoryItemCodec(ctrl *gomock.Controller) *MockMemoryItemCodec {
	mock := &MockMemoryItemCodec{ctrl: ctrl}
	mock.recorder = &MockMemoryItemCodecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryItemCodec) EXPECT() *MockMemoryItemCodecMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockMemoryItemCodec) Decode(data []byte) (MemoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", data)
	ret0, _ := ret[0].(MemoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decode indicates an expected call of Decode.
func (mr *MockMemoryItemCodecMockRecorder) Decode(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockMemoryItemCodec)(nil).Decode), data)
}

// Encode mocks base method.
func (m *MockMemoryItemCodec) Encode(item MemoryItem) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", item)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockMemoryItemCodecMockRecorder) Encode(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockMemoryItemCodec)(nil).Encode), item)
}

// MockMemoryStore is a mock of MemoryStore interface.
type MockMemoryStore struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryStoreMockRecorder
}

// MockMemoryStoreMockRecorder is the mock recorder for MockMemoryStore.
type MockMemoryStoreMockRecorder struct {
	mock *MockMemoryStore
}

// NewMockMemoryStore creates a new mock instance.
func NewMockMemoryStore(ctrl *gomock.Controller) *MockMemoryStore {
	mock := &MockMemoryStore{ctrl: ctrl}
	mock.recorder = &MockMemoryStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryStore) EXPECT() *MockMemoryStoreMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockMemoryStore) Clear(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockMemoryStoreMockRecorder) Clear(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockMemoryStore)(nil).Clear), ctx)
}

// Close mocks base method.
func (m *MockMemoryStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMemoryStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMemoryStore)(nil).Close))
}

// Load mocks base method.
func (m *MockMemoryStore) Load(ctx context.Context) ([]MemoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx)
	ret0, _ := ret[0].([]MemoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockMemoryStoreMockRecorder) Load(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockMemoryStore)(nil).Load), ctx)
}

// Store mocks base method.
func (m *MockMemoryStore) Store(ctx context.Context, item MemoryItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockMemoryStoreMockRecorder) Store(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockMemoryStore)(nil).Store), ctx, item)
}

// MockMemoryRetriever is a mock of MemoryRetriever interface.
type MockMemoryRetriever struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryRetrieverMockRecorder
}

// MockMemoryRetrieverMockRecorder is the mock recorder for MockMemoryRetriever.
type MockMemoryRetrieverMockRecorder struct {
	mock *MockMemoryRetriever
}

// NewMockMemoryRetriever creates a new mock instance.
func NewMockMemoryRetriever(ctrl *gomock.Controller) *MockMemoryRetriever {
	mock := &MockMemoryRetriever{ctrl: ctrl}
	mock.recorder = &MockMemoryRetrieverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryRetriever) EXPECT() *MockMemoryRetrieverMockRecorder {
	return m.recorder
}

// Retrieve mocks base method.
func (m *MockMemoryRetriever) Retrieve(ctx context.Context, options ...MemoryRetrieveOption) ([]MemoryItem, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Retrieve", varargs...)
	ret0, _ := ret[0].([]MemoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockMemoryRetrieverMockRecorder) Retrieve(ctx interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockMemoryRetriever)(nil).Retrieve), varargs...)
}

// MockMemory is a mock of Memory interface.
type MockMemory struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryMockRecorder
}

// MockMemoryMockRecorder is the mock recorder for MockMemory.
type MockMemoryMockRecorder struct {
	mock *MockMemory
}

// NewMockMemory creates a new mock instance.
func NewMockMemory(ctrl *gomock.Controller) *MockMemory {
	mock := &MockMemory{ctrl: ctrl}
	mock.recorder = &MockMemoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemory) EXPECT() *MockMemoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockMemory) Add(ctx context.Context, memory MemoryItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, memory)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockMemoryMockRecorder) Add(ctx, memory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockMemory)(nil).Add), ctx, memory)
}

// Reset mocks base method.
func (m *MockMemory) Reset() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset")
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockMemoryMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockMemory)(nil).Reset))
}

// Retrieve mocks base method.
func (m *MockMemory) Retrieve(ctx context.Context, options ...MemoryRetrieveOption) ([]MemoryItem, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Retrieve", varargs...)
	ret0, _ := ret[0].([]MemoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockMemoryMockRecorder) Retrieve(ctx interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockMemory)(nil).Retrieve), varargs...)
}

// MockMemoryItem is a mock of MemoryItem interface.
type MockMemoryItem struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryItemMockRecorder
}

// MockMemoryItemMockRecorder is the mock recorder for MockMemoryItem.
type MockMemoryItemMockRecorder struct {
	mock *MockMemoryItem
}

// NewMockMemoryItem creates a new mock instance.
func NewMockMemoryItem(ctrl *gomock.Controller) *MockMemoryItem {
	mock := &MockMemoryItem{ctrl: ctrl}
	mock.recorder = &MockMemoryItemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryItem) EXPECT() *MockMemoryItemMockRecorder {
	return m.recorder
}

// AsMessage mocks base method.
func (m *MockMemoryItem) AsMessage() (*llms.Message, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AsMessage")
	ret0, _ := ret[0].(*llms.Message)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// AsMessage indicates an expected call of AsMessage.
func (mr *MockMemoryItemMockRecorder) AsMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsMessage", reflect.TypeOf((*MockMemoryItem)(nil).AsMessage))
}

// GetContent mocks base method.
func (m *MockMemoryItem) GetContent() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent")
	ret0, _ := ret[0].(any)
	return ret0
}

// GetContent indicates an expected call of GetContent.
func (mr *MockMemoryItemMockRecorder) GetContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockMemoryItem)(nil).GetContent))
}

// GetCreatedAt mocks base method.
func (m *MockMemoryItem) GetCreatedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreatedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetCreatedAt indicates an expected call of GetCreatedAt.
func (mr *MockMemoryItemMockRecorder) GetCreatedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreatedAt", reflect.TypeOf((*MockMemoryItem)(nil).GetCreatedAt))
}

// GetId mocks base method.
func (m *MockMemoryItem) GetId() MemoryItemId {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(MemoryItemId)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockMemoryItemMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockMemoryItem)(nil).GetId))
}
